#!/usr/bin/with-contenv bash

# make necessary folders
mkdir -p /config \
         /downloads \
         /tv \

# cleanup pid if it exists
[[ -e /config/nzbdrone.pid ]] && \
	rm -rf /config/nzbdrone.pid

# recursive setting permissions
chown -R app:app \
	/opt/NzbDrone

  # permissions (non-recursive) on config and data directories
  chown app:app \
  /opt/NzbDrone \
  /config \
  /downloads \
  /tv
